---
title: "Social Equity Researcher"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

My name is Jose Cervantez and I am a current Pre-Doctoral Research Fellow at the UCLA Anderson School of Management. I will be applying to Organizational Behavior, Management and Social Psychology PhD programs in Fall 2021, with an anticipated start date of Fall 2022. My research is broadly focused on social equity and mobility issues. I am interested in how the individual traverses both occupational and social spaces while facing the threats of stereotype, discrimination, and prejudice.  

My website is built around two premises: 

1. Landing page for my research.

2. Learning space for statistics, programming, and technical skills. 

Since my research is built around mobility and equity, I am a large advocate for sharing knowledge and building others up. Feel free to look at my Resources tab for more information.

I'm always looking for collaborators, research discussions, and differences in opinion!